# Change these first
owner: Monakoweb # Your GitHub organization or username, where this repository lives
repo: upptime_ce # The name of this repository

sites:
  
  - name: SAMAI
    url: https://relatoria.consejodeestado.gov.co:8080/
  - name: SAMAI AZURE
    url: https://samai.azurewebsites.net/
  - name: Indice Electronico
    url: https://iedoc.consejodeestado.gov.co:448/
  - name: Vocabulario Controlado
    url: http://190.217.24.78:8888/tematres3/vocab/index.php
  - name: Buscador Tradicional CONSEJO
    url: http://190.217.24.55:8080/WebRelatoria/ce/index.xhtml
  - name: JCA CONSEJO
    url: https://relatoria.consejodeestado.gov.co:8088/
  - name: Ventanilla Azure
    url: ventanillavirtual.consejodeestado.gov.co
  - name: SAMAI AZURE-2
    url: samai.consejodeestado.gov.co
  - name: SAMAI JCA AZURE-2
    url: samaijca.consejodeestado.gov.co
  - name: INDICE MICRO
    url: https://iedoc.consejodeestado.gov.co:448/swagger.html
    
    
 
    
assigness:
- Monakoweb

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /
  baseUrl: /upptime_ce
  logoUrl: https://consejodeestado.gov.co/wp-content/uploads/2021/11/cde.png
  name: INSIGHTS CONSEJO DE ESTADO
  introTitle: "**I-CE** Monitor de actividad y estado de servicios"
  introMessage: 
  theme: dark
  #navbar:
   # - title: Status
    #  href: /
    #- title: GitHub
     # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
